/**
 * ピン統一の採用マシン＋AbCoaster／Booty Builder／リフォーマー
 * （プレートは例外指定のみ）
 */
export const CURATED_RESISTANCE_MACHINES = [
  {
    id: "hoist_rs2700_chin_dip_assist",
    name: "HOIST　チン／ディップアシスト（ROC-IT）",
    brand: "HOIST",
    model: "RS-2700",
    zone: "初心者",
    genre: "stack",
    width_cm: 170,
    length_cm: 125,
    height_cm: 246,
    qty: 1,
    load_type: "pin",
    note: "ピンタイプ。アシスト／ノンアシスト両対応",
    link: "https://www.hoistfitness.com/products/rs-2700-chin-dip-assist",
    image_url: "https://www.hoistfitness.com/cdn/shop/files/RS-2700_ChinDipAssist_Platinum_Black_1.png",
  },
  {
    id: "cybex_ion_biceps_triceps",
    name: "Cybex　バイセップス／トライセップス（Ion）",
    brand: "Cybex",
    model: "CI-BT",
    zone: "腕",
    genre: "stack",
    width_cm: 109,
    length_cm: 124,
    height_cm: 135,
    qty: 1,
    load_type: "pin",
    note: "ピンタイプ2in1（LF Axiom相当）。カール＋エクステンション1台",
    link: "https://www.lifefitness.com/en-us/catalog/cybex/cybex-products/cybex-ion-series-biceps-triceps",
    image_url:
      "https://www.lifefitness.com/resource/image/2525868/portrait_ratio1x1/1200/1200/b1c5c5c0f0c5f0c5f0c5f0c5f0c5f0c5/CYBEX-Ion-Biceps-Triceps.jpg",
  },
  {
    id: "matrix_ultra_prone_leg_curl",
    name: "Matrix　プローンレッグカール（Ultra）",
    brand: "Matrix",
    model: "G7-S73",
    zone: "脚",
    genre: "stack",
    width_cm: 112,
    length_cm: 173,
    height_cm: 135,
    qty: 1,
    load_type: "pin",
    note: "ピンタイプ。うつ伏せハム",
    link: "https://www.johnsonfitness.com.au/products/matrix-ultra-prone-leg-curl",
    image_url:
      "https://images.jhtassets.com/e8e8e8e8/matrix-ultra-prone-leg-curl.jpg",
  },
  {
    id: "booty_builder_platinum",
    name: "Booty Builder　ヒップスラスト（Platinum V4）",
    brand: "Booty Builder",
    model: "Platinum V4",
    zone: "Glute",
    genre: "plate",
    width_cm: 144,
    length_cm: 170,
    height_cm: 78,
    qty: 1,
    load_type: "plate",
    note: "ヒップ系はBooty Builder。プレートロード例外",
    link: "https://bootybuilder.com/product/booty-builder-platinum/",
    image_url: "https://bootybuilder.com/wp-content/uploads/2023/11/Booty-Builder-Platinum-V4.jpg",
  },
  {
    id: "ab_coaster_cs1500",
    name: "AbCoaster　CS1500",
    brand: "The Abs Company",
    model: "CS1500",
    zone: "初心者",
    genre: "plate",
    width_cm: 69,
    length_cm: 134,
    height_cm: 135,
    qty: 1,
    load_type: "plate",
    note: "ゴールドジム定番。プレート追加可（唯一プレート例外）",
    link: "https://fitnessshop.jp/products/603411000",
    image_url: "",
  },
  {
    id: "pilates_reformer",
    name: "ピラティスリフォーマー",
    brand: "",
    model: "130×60",
    zone: "ピラティス",
    genre: "pilates",
    width_cm: 130,
    length_cm: 60,
    height_cm: null,
    qty: 1,
    load_type: "bodyweight",
    note: "配置寸法 130×60cm",
    link: "",
    local_image: true,
  },
];

/** シート側の旧案を差し替えるため除外する名称 */
export const SKIP_NEW_SHEET_NAMES = new Set([
  "Assist Dip Chin",
  "Assist Dip & Chin",
  "Pure Kraft Biceps Curl Dual",
  "Pure Kraft Triceps Extension",
  "Pure Kraft Lying Leg Curl",
  "Hip Thrust Elite",
  "Abdominal Crunch",
  // 既存CYBEX脚があるのでHS Select脚は不要
  "Hammer Strength Select Leg Extension",
  "Hammer Strength Select Leg Curl",
]);
